// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIs3Ica5OIms0U5FKVwZvx_TXjV9Ok5YA',
    appId: '1:865609841747:web:29beae5a0fab0e28fb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    authDomain: 'mekhemar-19f76.firebaseapp.com',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
    measurementId: 'G-VXP4F31BKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYAnNl_hUWDyx7MwjW1HWSY1hrnbwMb8',
    appId: '1:865609841747:android:b160fe1988155c5bfb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI-r52s7-F3hrROekC1JRoi08q35DO50E',
    appId: '1:865609841747:ios:3a48bab3e40a422bfb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
    androidClientId: '865609841747-oika0ua91md90m2quo67jvjpu1louq4u.apps.googleusercontent.com',
    iosClientId: '865609841747-dmj9pcgf4jej4fegg2pg4j9ghmjte5kk.apps.googleusercontent.com',
    iosBundleId: 'com.benhauniversity.mekhemar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI-r52s7-F3hrROekC1JRoi08q35DO50E',
    appId: '1:865609841747:ios:3a48bab3e40a422bfb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
    androidClientId: '865609841747-oika0ua91md90m2quo67jvjpu1louq4u.apps.googleusercontent.com',
    iosClientId: '865609841747-dmj9pcgf4jej4fegg2pg4j9ghmjte5kk.apps.googleusercontent.com',
    iosBundleId: 'com.benhauniversity.mekhemar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIs3Ica5OIms0U5FKVwZvx_TXjV9Ok5YA',
    appId: '1:865609841747:web:29beae5a0fab0e28fb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    authDomain: 'mekhemar-19f76.firebaseapp.com',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
    measurementId: 'G-VXP4F31BKP',
  );

}