// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIs3Ica5OIms0U5FKVwZvx_TXjV9Ok5YA',
    appId: '1:865609841747:web:dc61fc662949e3e8fb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    authDomain: 'mekhemar-19f76.firebaseapp.com',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
    measurementId: 'G-XT68KR7Z0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYAnNl_hUWDyx7MwjW1HWSY1hrnbwMb8',
    appId: '1:865609841747:android:fa60fdd9afcf9f8bfb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI-r52s7-F3hrROekC1JRoi08q35DO50E',
    appId: '1:865609841747:ios:90a379bcfd31ff7bfb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
    iosClientId: '865609841747-ekqs63be032a4j9mhkajlbqck5p15o6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI-r52s7-F3hrROekC1JRoi08q35DO50E',
    appId: '1:865609841747:ios:90a379bcfd31ff7bfb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
    iosClientId: '865609841747-ekqs63be032a4j9mhkajlbqck5p15o6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIs3Ica5OIms0U5FKVwZvx_TXjV9Ok5YA',
    appId: '1:865609841747:web:41a0b8033ff66ce9fb1aa6',
    messagingSenderId: '865609841747',
    projectId: 'mekhemar-19f76',
    authDomain: 'mekhemar-19f76.firebaseapp.com',
    storageBucket: 'mekhemar-19f76.firebasestorage.app',
    measurementId: 'G-L68FFB3VEK',
  );
}
